image: microsoft/dotnet:sdk

pipelines:
  branches: 
    master:
      - step:
          name: Build Server
          caches:
            - dotnetcore
          script:
            - export PROJECT_NAME=Api
            - dotnet publish backend/src/$PROJECT_NAME -c Release -o ./dist
            - apt-get update
            - apt-get install -y rsync            
            - rsync -rvP --del --exclude 'wwwroot*' ./backend/src/$PROJECT_NAME/dist/ ubuntu@academia.proseek.com.br:///var/aspnetcore/academia-api
            - ssh ubuntu@academia.proseek.com.br sudo systemctl restart academia-api-mirror.service    
            - ssh ubuntu@academia.proseek.com.br sudo systemctl restart academia-api-charlie.service            
      - step:
          image: node:12.8.1
          name: Build Frontend
          caches:
            - localnode
          script:
            - cd frontend
            - npm install
            - apt-get update
            - apt-get install -y rsync
            - npm run build:mirror
            - rsync -rvP --del ./dist/frontend/ ubuntu@academia.proseek.com.br://var/www/academia/mirror/
            - npm run build:charlie
            - rsync -rvP --del ./dist/frontend/ ubuntu@academia.proseek.com.br://var/www/academia/charliemoney/
    b2b:
      - step:
          name: Build Server
          caches:
            - dotnetcore
          script:
            - export PROJECT_NAME=Api
            - dotnet publish backend/src/$PROJECT_NAME -c Release -o ./dist
            - apt-get update
            - apt-get install -y rsync            
            - rsync -rvP --del --exclude 'wwwroot*' ./backend/src/$PROJECT_NAME/dist/ ubuntu@academia.proseek.com.br:///var/aspnetcore/academia-api-b2b
            - ssh ubuntu@academia.proseek.com.br sudo systemctl restart academia-api.service        
      - step:
          image: node:10.13.0
          name: Build Frontend
          caches:
            - localnode
          script:
            - cd frontend
            - npm install
            - npm run build:hmg
            - apt-get update
            - apt-get install -y rsync
            - rsync -rvP --del ./dist/frontend/ ubuntu@academia.proseek.com.br://var/www/academia/site/
    develop:
      - step:
          name: Build Server
          caches:
            - dotnetcore
          script:
            - export PROJECT_NAME=Api
            - dotnet publish backend/src/$PROJECT_NAME -c Release -o ./dist
            - apt-get update
            - apt-get install -y rsync            
            - rsync -rvP --del --exclude 'wwwroot*' ./backend/src/$PROJECT_NAME/dist/ ubuntu@dev.academia.tg4.com.br:///var/aspnetcore/academia-api-staging
            - ssh ubuntu@dev.academia.tg4.com.br sudo systemctl restart academia-api-staging.service    
      - step:
          image: node:10.13.0
          name: Build Frontend
          caches:
            - localnode
          script:
            - cd frontend
            - npm install
            - npm run build:staging
            - apt-get update
            - apt-get install -y rsync
            - rsync -rvP --del ./dist/frontend/ ubuntu@dev.academia.tg4.com.br://var/www/academia/staging/
    b2b-develop:
      - step:
          name: Build Server
          caches:
            - dotnetcore
          script:
            - export PROJECT_NAME=Api
            - dotnet publish backend/src/$PROJECT_NAME -c Release -o ./dist
            - apt-get update
            - apt-get install -y rsync            
            - rsync -rvP --del --exclude 'wwwroot*' ./backend/src/$PROJECT_NAME/dist/ ubuntu@dev.academia.tg4.com.br:///var/aspnetcore/academia-api-b2b-hmg
            - ssh ubuntu@dev.academia.tg4.com.br sudo systemctl restart academia-api-b2b-hmg.service    
      - step:
          image: node:10.13.0
          name: Build Frontend
          caches:
            - localnode
          script:
            - cd frontend
            - npm install
            - npm run build:b2b-hmg
            - apt-get update
            - apt-get install -y rsync
            - rsync -rvP --del ./dist/frontend/ ubuntu@dev.academia.tg4.com.br://var/www/academia/b2b-hmg/
definitions:
  caches:
    localnode: frontend/node_modules