name: CI

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on:
  push:
    branches:
      - master



env:
  NODE_VERSION: '10.13.0'                # set this to the node version to use
  DOTNET_VERSION: 2.2.108                # set this to the dotnet version to use

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setting .net version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.700
        

        
 #   - name: Build Server
 #    run:  |
 #       dotnet build ./backend/src/Api --configuration Release --output ./output
        
    - name: dotnet publish 
      run: |
        dotnet publish backend/src/Api -c Release -o ./dist
        
    - name: Display status from deploy
      run: echo "Deploy 1"
        
    - name: Deploy to server
      id: deploy2
      uses: Pendect/action-rsyncer@v1.1.0
      env:
       DEPLOY_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      with:
        flags: '-rvP --del'
        options: "--exclude 'wwwroot*'"
        ssh_options: './output'
        src: 'public/'
        dest: 'ubuntu@107.21.157.253:///var/aspnetcore/academia-api'
        
    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"
          
  #  - name: dotnet deploy 
  #    run: |
  #      - sudo apt-get update
     #   - sudo apt-get install -y rsync
      #  - rsync -rvP --del --exclude 'wwwroot*' ./backend/src/Api/dist/ ubuntu@107.21.157.253:///var/aspnetcore/academia-api        

            
    - name: Set Node Version
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm run build:staging
        sudo apt-get update
        sudo apt-get install -y rsync
        rsync -rvP --del ./dist/frontend/ ubuntu@107.21.157.253://var/www/academia/staging/
        

